#!/usr/bin/env bash
# Does the experiment 2 framing result carry over beyond direct judging?
#
# Four cells at n=300 on the primary judge: debate and consultancy, each under
# neutral framing and under experiment 1's original wording, so the comparison
# is within-run rather than across repositories.
#
# Do NOT edit this file while it is running. Bash reads scripts incrementally by
# byte offset, and rewriting it underneath a live run makes the interpreter
# resume in the wrong place. We learned that the expensive way.

set -uo pipefail
cd "$(dirname "$0")"

N=300
JUDGE=ollama/qwen2.5:7b
PY=./.venv/bin
LOG=carryover.log
export OPENAI_API_KEY=ollama

for CELL in consultancy_cipher_neutral consultancy_cipher_warned \
            debate_cipher_neutral debate_cipher_warned; do
  echo "[$(date -u +%H:%M:%S)] START $CELL" | tee -a "$LOG"
  "$PY/inspect" eval "collapse/task.py@${CELL}" --model "$JUDGE" -T n="$N" \
      --log-dir collapse/logs-carryover > /dev/null 2>&1 || true
  echo "[$(date -u +%H:%M:%S)] DONE  $CELL" | tee -a "$LOG"
done

echo "[$(date -u +%H:%M:%S)] ALL DONE" | tee -a "$LOG"
