#!/usr/bin/env bash
# Confirmatory run for collapse/PREREGISTRATION.md (experiment 2).
#
# Six cells at n=300 for each of two judges. Results append to results.tsv as
# each cell completes, so a partial run is still usable. Cells are ordered so
# the two that identify the confound come first.
#
# Usage: ./run_confirmatory.sh

# Do NOT edit this file while it is running. Bash reads scripts incrementally by
# byte offset; rewriting it underneath a live run makes the interpreter resume in
# the wrong place. We did exactly that and it re-ran a finished cell.

set -uo pipefail
cd "$(dirname "$0")"

N=300
PY=./.venv/bin
OUT=collapse/results.tsv
LOG=collapse/confirmatory.log
export OPENAI_API_KEY=ollama

if [ ! -f "$OUT" ]; then
  printf 'judge\tcell\tn\tyes_rate\taccuracy\tstderr\ttimestamp\n' > "$OUT"
fi

run_cell () {
  local judge="$1" cell="$2"
  echo "[$(date -u +%H:%M:%S)] START $judge $cell" | tee -a "$LOG"

  local raw acc se
  raw=$("$PY/inspect" eval "collapse/task.py@${cell}" --model "$judge" -T n="$N" --log-dir collapse/logs 2>&1) || true
  acc=$(echo "$raw" | grep -E '^accuracy' | awk '{print $2}' | head -1)
  se=$(echo "$raw"  | grep -E '^stderr'   | awk '{print $2}' | head -1)

  if [ -z "$acc" ]; then
    echo "[$(date -u +%H:%M:%S)] FAIL  $judge $cell" | tee -a "$LOG"
    echo "$raw" | tail -5 >> "$LOG"
    return
  fi

  # YES rate is the primary metric and Inspect does not report it, so read it
  # back out of the log this cell just wrote.
  local yes
  yes=$("$PY/python" -c "
from inspect_ai.log import read_eval_log
import glob,os
# Inspect writes task names with hyphens, not underscores.
pat='collapse/logs/*'+'${cell}'.replace('_','-')+'*.eval'
c=glob.glob(pat)
if not c: raise SystemExit('no log matching '+pat)
p=max(c, key=os.path.getmtime)
log=read_eval_log(p); ss=log.samples or []
y=sum(1 for s in ss if getattr(next(iter((s.scores or {}).values()),None),'answer',None)=='YES')
print(f'{y/len(ss):.4f}' if ss else '')
")

  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$judge" "$cell" "$N" "$yes" "$acc" "$se" "$(date -u +%FT%TZ)" >> "$OUT"
  echo "[$(date -u +%H:%M:%S)] DONE  $judge $cell yes=$yes acc=$acc" | tee -a "$LOG"
}

echo "=== replication tests (prompts must match experiment 1) ===" | tee -a "$LOG"
"$PY/python" -m pytest tests/ -q 2>&1 | tail -3 | tee -a "$LOG"

for JUDGE in ollama/qwen2.5:7b ollama/qwen2.5:3b; do
  echo "=== judge $JUDGE ===" | tee -a "$LOG"
  # The two cells that identify the confound run first.
  run_cell "$JUDGE" cipher_neutral
  run_cell "$JUDGE" absent_warned
  run_cell "$JUDGE" cipher_warned
  run_cell "$JUDGE" absent_neutral
  run_cell "$JUDGE" e1_obscured
  run_cell "$JUDGE" e1_none
done

echo "[$(date -u +%H:%M:%S)] ALL DONE" | tee -a "$LOG"
column -t -s "$(printf '\t')" "$OUT"
